django/demos/blobblog/blobblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Ajout des urls du blog
    path('', include('blog.url')),
    path("admin/", admin.site.urls),
    # Ajout des urls de l'application auth
    path('accounts/', include('django.contrib.auth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
]

django/demos/blobblog/blog/models.py
from django.db import models

# Create your models here.

from datetime import date
from django.urls import reverse
from django.contrib.auth.models import User  # Importer la classe User de l'app Auth


class BlogAuthor(models.Model):
    """
    Représente un blogger
    """
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=400, help_text="Entrer votre biographie")

    class Meta:
        ordering = ["user", "bio"]

    def get_absolute_url(self):
        """
        Retourne les blogs d'un utilisateurs
        """
        return reverse('blog:blogs-by-author', args=[str(self.id)])

    def __str__(self):
        """
        Surcharge de la dunder string
        """
        return self.user.username


class Blog(models.Model):
    """
    Model représentant un post d'un utilisateur
    """
    name = models.CharField(max_length=200)
    # Ajout de la contrainte One-To-Many
    description = models.TextField(max_length=2000, help_text="Entrer une description")
    post_date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(BlogAuthor, on_delete=models.SET_NULL, null=True)

    # Ajout du trie par défaut des entités
    class Meta:
        ordering = ["-post_date"]
        indexes = [
            models.Index(fields=['post_date'])
        ]

    def get_absolute_url(self):
        """
        Retourne l'url d'un post précis
        """
        return reverse('blog:blog-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class BlogComment(models.Model):
    """
    Représente un commentaire sur un post
    """
    description = models.TextField(max_length=1000, help_text="Enter comment about blog here.")
    post_date = models.DateTimeField(auto_now_add=True)
    # Ajout des contraintes de clés étrangères
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["post_date"]

    def __str__(self):
        """
        Renvoie une description minifiée si la taille dépasse 75 caractères
        """
        len_title = 75
        if len(self.description) > len_title:
            titlestring = self.description[:len_title] + '...'
        else:
            titlestring = self.description
        return titlestring

django/demos/blobblog/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from django.core.cache import cache
from django.views import generic
from .models import Blog, BlogAuthor, BlogComment
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse
from django.contrib.auth.models import User  # Blog author or commenter


def index(request):
    """
    Vue pour la page d'accueil
    """
    return render(
        request,
        'index.html',
    )


class BlogListView(generic.ListView):
    """
    Classe générique pour afficher les posts à l'aide d'une pagination
    """
    model = Blog
    paginate_by = 5


class BlogListByAuthorView(generic.ListView):
    """
    Classe générique pour afficher les posts d'un auteur
    """
    model = Blog
    paginate_by = 5
    template_name = 'blog/blog_list_by_author.html'

    def get_queryset(self):
        """
        Return une liste de post créé par un auteur en récupérant l'id dans l'URL
        """
        id = self.kwargs['pk']
        target_author = get_object_or_404(BlogAuthor, pk=id)
        
        # accès aux blogs dans le cache par sa clé
        blogs = cache.get('blogs')

        print(blogs, "access to the cache")
        # blogs = cache.get_or_set('blogs', Blog.objects.filter(author=target_author), 60 * 2)

        if blogs is None:
            blogs = Blog.objects.filter(author=target_author)
            print(blogs, "after the request")
            cache.set('blogs', blogs, 60 * 2)
        
        return blogs

    def get_context_data(self, **kwargs):
        """
        Ajout de l'auteur dans le context pour pouvoir l'afficher
        """
        # Appel de l'implémentation de la classe parent du context
        context = super(BlogListByAuthorView, self).get_context_data(**kwargs)
        # Récupération de l'auteur à l'aide du paramètre passé dans la requête
        context['blogger'] = get_object_or_404(BlogAuthor, pk=self.kwargs['pk'])
        return context


class BlogDetailView(generic.DetailView):
    """
    Classe générique pour voir le détail d'un post
    """
    model = Blog


class BloggerListView(generic.ListView):
    """
   Classe générique pour afficher les auteurs
    """
    model = BlogAuthor
    paginate_by = 5


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    """
    Formulaire de création d'un commentaire avec connexion obligatoire
    """
    model = BlogComment
    fields = ['description', ]

    def get_context_data(self, **kwargs):
        """
        Ajouter le titre du blog associé dans le formulaire
        """
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        # Récupérer l'id du post et l'ajouter dans le context
        context['blog'] = get_object_or_404(Blog, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Ajouter l'auteur et le post avant validation du formulaire
        """
        # Récupération de l'utilisateur depuis la requête
        form.instance.author = self.request.user
        # Association du blog avec l'id passé en URL
        form.instance.blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # Appel de la méthod de la classe parente pour la validation du formulaire
        return super(BlogCommentCreate, self).form_valid(form)

    def get_success_url(self):
        """
        Après validation du formulaire, redirection vers de détail du blog
        """
        return reverse('blog:blog-detail', kwargs={'pk': self.kwargs['pk'], })
    
def get_blog_and_author(request, id: int):
    blog = Blog.objects.select_related('author').get(id=id)
    print(blog.author)
    return render(request, 'index.html')

django/demos/blobblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>

    {% block title %}<title>BlobBlog</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    {# Utilisation de url pour créer des liens avec le nom de l'url #}
                    <li><a href="{% url 'blog:index' %}">Accueil</a></li>
                    <li><a href="{% url 'blog:blogs' %}">Les posts</a></li>
                    <li><a href="{% url 'blog:bloggers' %}">les auteurs</a></li>
                </ul>

                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Se déconnecter</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Se connecter</a></li>
                    {% endif %}
                </ul>

            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            {% block content %}{% endblock %}

            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Précédent</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Suivant</a>
                {% endif %}
            </span>
                    </div>
                {% endif %}
            {% endblock %}

        </div>
    </div>

</div>
</body>
</html>

django/demos/blobblog/blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ blog.name }}</h1>
<p><strong>Post date</strong> {{ blog.post_date }}</p>
<p><strong>Author:</strong> <a href="{% url 'blog:blogs-by-author' blog.author.pk %}">{{ blog.author }}</a></p>
<p><strong>Description:</strong></p>
<p style="white-space:pre-wrap;">{{ blog.description }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Comments</h4>

{% for comment in blog.blogcomment_set.all %}
<hr>
<p>{{comment.author}} ({{comment.post_date}}) - {{comment.description}}</p>
{% endfor %}
<hr>
{% if user.is_authenticated %}
  <a href="{% url 'blog:blog-comment' blog.id %}">Add a new comment</a></p>
{% else %}
  <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
{% endif %} 


</div>
{% endblock %}

django/demos/blobblog/blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Liste des postes</h1>

    {% if blog_list %}
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}}) — <a href="{% url 'blog:blogs-by-author' blog.author.pk %}">{{ blog.author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>Aucun post trouvé :(</p>
    {% endif %}       
{% endblock %}

django/demos/blobblog/blog/templates/blog/blog_list_by_author.html
{% extends "base.html" %}

{% block content %}
    <h1>Auteur: {{blogger}}</h1>
    
    <h3>Bio</h3>
    
    <p>{{blogger.bio}}</p>
    
    

    {% if blog_list %}
    <h3>Liste des posts</h3>
    <ul>

      {% for blog in blog_list %}
      <li>
        <a href="{{ blog.get_absolute_url }}">{{ blog.name }}</a> ({{blog.post_date}})</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>L'auteur n'a rien posté pour le moment</p>
    {% endif %}       
{% endblock %}

django/demos/blobblog/blog/templates/blog/blogauthor_list.html
{% extends "base.html" %}

{% block content %}
    <h1>All bloggers</h1>

    {% if blogauthor_list %}
    <ul>

      {% for author in blogauthor_list %}
      <li>
        <a href="{% url 'blog:blogs-by-author' author.pk %}">{{ author }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>Aucun auteur pour le moment</p>
    {% endif %}       
{% endblock %}

django/demos/blobblog/blog/templates/blog/blogcomment_form.html
{% extends "base.html" %}

{% block content %}
<p>Créer un commentaire pour le post : <a href="{% url 'blog:blog-detail' blog.pk %}">{{blog.name}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

django/demos/blobblog/blog/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Blob Blog !</h1>

<p>Bienvenue sur Blog Blog.</p>


{% load cache %}
{% cache 180 index %}
<h2>Patate</h2>
<p>Ci-dessous une belle photo de patate </p>
{% endcache %}

<div>
{% load static %}
<img src="{% static "img/une-patate.jpg" %}" alt="ma patate" style="height:540px;"/>
</div>

{% endblock %}