django/demos/myblog/blog/urls.py
from django.urls import path
from . import views

# Variable qui permet la résolution d'URL dans les templates à l'aide du nom
app_name = 'blog'

urlpatterns = [
    # path prend en paramètre la route, une vue, et un nom (facultatif)
    path('', views.index, name="index"),
    # Utiliser des paramètres dans un URL
    path('<int:num>', views.number, name="number"),
    path('test', views.test_template, name="test"),
    path('blogs', views.get_all, name="blogs"),
    path('blogs/<int:id>', views.blog_detail, name="blog-detail"),
    path('blogs-generic', views.BlogListView.as_view()),
    path('blogs/create', views.BlogCreateView.as_view(), name="blog-create"),
    path('blogs/<int:blog_id>/comments/create', views.create_comment, name="create-comment")
]

django/demos/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path("admin/", admin.site.urls),
]

django/demos/myblog/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Blog(models.Model):
    """
    représentation d'un blog
    """
    name = models.TextField(max_length=100, help_text="entrer le nom du blog")
    author = models.TextField(max_length=100, help_text="saisir le nom de l'auteur")
    created_at = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def get_absolute_url(self):
        return reverse("blog:blog-detail", kwargs={"id": self.pk})
    

    def __str__(self) -> str:
        return self.name

class Comment(models.Model):
    """
    représentation d'une commentaire sur un blog
    """
    description = models.TextField(max_length=200, help_text="saisir le commentaire")
    posted_at = models.DateField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    class Meta:
        ordering = ["posted_at"]

    def __str__(self) -> str:
        return self.description

django/demos/myblog/blog/forms.py
from django.forms import ModelForm
from .models import Comment

# Création d'un formulaire basé sur un modèle
class CommentForm(ModelForm):
    class Meta:
        # modèle à utiliser
        model = Comment
        # champs requis pour le formulaire
        fields = ['description']

django/demos/myblog/blog/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm
from .models import Blog, Comment
from django.views.generic import ListView, CreateView

# Create your views here.
def index(request): 

    villes = ['paris', 'roubaix', 'toulouse']

    return render(request, 'blog/index.html', {'prenom': 'arthur', 'villes': villes})

def number(request, num):
    return HttpResponse(f"{num}")

def test_template(request):
    b = Blog(name="mon blog", author="arthur")
    b.save()
    return HttpResponse("blog créé")

def get_all(request):
    """
    Retourne tous les blogs de la base de données
    """
    blogs = Blog.objects.all()
    return render(request, 'blog/blog-list.html', {'blogs': blogs})

def blog_detail(request, id: int):
    """
    Affiche le détail d'un blog
    """

    blog = get_object_or_404(Blog, pk=id)
    blog.comment = blog.comment_set.all()

    return render(request, 'blog/blog-detail.html', {'blog': blog})

class BlogListView(ListView):
    context_object_name = "blogs"
    model = Blog
    template_name = "blog/blog-list.html"


class BlogCreateView(CreateView):
    model = Blog
    fields = ['name', 'author']

def create_comment(request, blog_id: int):

    print(request.method)

    if request.method == 'GET':

        form = CommentForm()

        return render(request, 'blog/create-comment.html', {'form': form})

    if request.method == 'POST':
        
        blog = Blog.objects.get(pk=blog_id)

        comment = Comment(blog=blog)

        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            form.save()
        return redirect('blog:blog-detail', id=blog_id)

    raise Http404("Wrong http method")

django/demos/myblog/blog/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>{% block title %}My blog{% endblock %}</title>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'blog:index' %}">My Blog</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {# url permet de rediriger vers un url à l'aide de son nom (name) #}
                  <a class="nav-link active" aria-current="page" href="{% url 'blog:index' %}">Home</a>
                  <a class="nav-link" href="{% url 'blog:blogs' %}">blogs</a>
                  <a class="nav-link" href="#">author</a>
                </div>
              </div>
            </div>
          </nav>
    </header>

    <main>
        <div id="content" class="container">
            {% block content %}{% endblock %}
        </div>
    </main>

</body>
</html>

django/demos/myblog/blog/templates/blog/blog-detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ blog }}</h2>
<p> {{blog.author }} </p>

<div>
    {% for comment in blog.comment %}
    <p>
        {{comment}}
    </p>     
    {% endfor %}
</div>

{% endblock %}

django/demos/myblog/blog/templates/blog/blog-list.html
{% extends 'base.html' %}

{% block content %}

<h1>blogs</h1>

<a class="button" href="{% url 'blog:blog-create' %}">créer un blog</a>

{% if blogs %}

{% for blog in blogs %}

<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ blog }}</h5>
      <a href="{{ blog.get_absolute_url }}" class="btn btn-primary">détail du blog</a>
    </div>
  </div>

{% endfor %}

{% else %}

<p> Aucun blog à afficher </p>

{% endif %}


{% endblock %}

django/demos/myblog/blog/templates/blog/blog_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

django/demos/myblog/blog/templates/blog/create-comment.html
{% extends 'base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

django/demos/myblog/blog/templates/blog/index.html
{% extends 'base.html' %} 

{% block title %} Ma page d'accueil {% endblock %} 

{% block content %}

<h1>Bienvenue sur mon blog</h1>

<p>Amusez bien à parcourir les articles</p>

<p>{{ prenom }}</p>

{% if villes %}

<ul>
  {% for ville in villes %}
  <li>{{ ville|title }}</li>
  {% endfor %}
</ul>

{% else %}

<p>Aucune ville</p>

{% endif %}

{% endblock %}