flask/demos/blog-advanced/blobblog/blog/models.py
from .. import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(75), nullable=False)
    content = db.Column(db.String(200), nullable=False)
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, onupdate=db.func.now())

flask/demos/blog-advanced/blobblog/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import Length, DataRequired


class PostForm(FlaskForm):
    title = StringField('title', validators=[Length(min=3, max=50, message='title should be 3 to 50 characters')])
    content = StringField('content', validators=[DataRequired()])

flask/demos/blog-advanced/blobblog/__init__.py
import click
from flask import Flask
from flask.cli import with_appcontext
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = "45f1a0c0-d026-4390-b637-cb451b35b403-8edb2384-4cea-4cf8-89e6-a70722f9d583"
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"

    # Add init db command to flask cli
    app.cli.add_command(init_db_command)

    # import blog blueprint to the app
    from .blog import blog as blog_blueprint
    app.register_blueprint(blog_blueprint)

    # import auth blueprint to the app
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    db.init_app(app)

    return app


def init_db():
    db.drop_all()
    db.create_all()


@click.command('init-db')
@with_appcontext
def init_db_command():
    init_db()
    click.echo('database initialized')

flask/demos/blog-advanced/blobblog/blog/__init__.py
from .views import blog

flask/demos/blog-advanced/blobblog/blog/views.py
from flask import render_template, Blueprint, redirect, url_for, flash, abort, request
from .models import Post
from .. import db
from .forms import PostForm

blog = Blueprint('blog', __name__)


@blog.route('/')
def index():
    posts = db.session.execute(db.select(Post).order_by(Post.created_at)).scalars()
    return render_template('index.html', posts=posts)


@blog.route('/create', methods=('GET', 'POST'))
def create():
    """creation d'un post"""
    form = PostForm()

    if form.validate_on_submit():
        post = Post()
        form.populate_obj(post)
        db.session.add(post)
        db.session.commit()
        flash('post created')
        return redirect(url_for('blog.index'))

    return render_template('blog/create.html', form=form)


@blog.get('/<int:id>/update')
def update(id: int):
    """maj d'un post"""
    post = db.session.get(Post, id)

    if post is None:
        abort(404)

    form = PostForm(obj=post)

    return render_template('blog/update.html', form=form)


@blog.post('/<int:id>/update')
def update_post(id: int):
    form = PostForm()

    post = db.session.get(Post, id)

    if post is None:
        abort(404)

    if form.validate_on_submit():
        form.populate_obj(post)
        db.session.commit()
        flash('post updated')
        return redirect(url_for('blog.index'))

    return render_template('blog/update.html', form=form)


@blog.route('/<int:id>/delete')
def delete(id: int):
    post = db.session.get(Post, id)
    db.session.delete(post)
    db.session.commit()
    flash('post deleted')
    return redirect(url_for('blog.index'))

flask/demos/blog-advanced/blobblog/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {#  load files from static folder  #}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" defer></script>

    {#  block to add title  #}
    <title>{% block title %} {% endblock %} - blog</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="#">BlobBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('blog.index') }}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Blogs</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-secondary" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container my-3">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

flask/demos/blog-advanced/blobblog/templates/blog/create.html
{% extends 'base.html' %}

{% block title %} create post {% endblock %}

{% block content %}
        <div class="container text-center mt-3">
        <div class="row">
            <div class="col-8 offset-2">
                <form method="post">
                    {{ form.csrf_token }}
                    <div class="form-group mb-3">
                        {{ form.title.label }} {{ form.title(class_="form-control") }}
                        {% if form.title.errors %}
                            {% for error in form.title.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.content.label }} {{ form.content(class_="form-control") }}

                        {% if form.content.errors %}
                            {% for error in form.content.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary mb-3">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

flask/demos/blog-advanced/blobblog/templates/blog/update.html
{% extends 'blog/create.html' %}

{% block title %} update post {% endblock %}

flask/demos/blog-advanced/blobblog/templates/index.html
{% extends 'base.html' %}

{% block title %} index {% endblock %}

{% block content %}

    <div class="mb-2">
        <a href="{{ url_for('blog.create') }}" class="btn btn-primary">create a post</a>
    </div>

    {% if posts %}
        {% for post in posts %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content }}</p>
                    <p class="card-text">{{ post.created_at }}</p>
                    <a href="{{ url_for('blog.update', id=post.id) }}" class="card-link">update</a>
                    <a href="{{ url_for('blog.delete', id=post.id) }}" class="card-link">delete</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}